//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.OrderManager = new HashSet<OrderManager>();
            this.Sales = new HashSet<Sales>();
        }
    
        public int CustomerId { get; set; }
        public string Customername { get; set; }
        public string Referred { get; set; }
        public string Zip_code { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Fax { get; set; }
        public string Contact { get; set; }
        public string Concat_phone { get; set; }
        public string Email { get; set; }
        public string Bank { get; set; }
        public string BankId { get; set; }
    
        public virtual ICollection<OrderManager> OrderManager { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
