//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Employees = new HashSet<Employees>();
            this.Material = new HashSet<Material>();
            this.Product = new HashSet<Product>();
            this.Users = new HashSet<Users>();
            this.Leave = new HashSet<Leave>();
            this.Shif = new HashSet<Shif>();
        }
    
        public int DepartmentId { get; set; }
        public string Departmentname { get; set; }
        public string DepartmentReadname { get; set; }
    
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<Material> Material { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<Leave> Leave { get; set; }
        public virtual ICollection<Shif> Shif { get; set; }
    }
}
