//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public Goods()
        {
            this.Material = new HashSet<Material>();
            this.Purchase_order = new HashSet<Purchase_order>();
        }
    
        public int Goodsid { get; set; }
        public string Goodsname { get; set; }
        public string Goodsjieche { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Origin { get; set; }
        public string Specifications { get; set; }
        public string Packaging { get; set; }
        public string Batch_number { get; set; }
        public string Titanic { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> Categoryid { get; set; }
        public string Tips { get; set; }
    
        public virtual Lnven Lnven { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<Material> Material { get; set; }
        public virtual ICollection<Purchase_order> Purchase_order { get; set; }
    }
}
