//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_inventory
    {
        public Goods_inventory()
        {
            this.Goods_Delivery = new HashSet<Goods_Delivery>();
        }
    
        public int InventoryId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Unit { get; set; }
        public string Suppliername { get; set; }
        public string Inventory_type { get; set; }
        public Nullable<int> Invenid { get; set; }
        public Nullable<int> ProduPutid { get; set; }
        public Nullable<int> Inventory { get; set; }
    
        public virtual ICollection<Goods_Delivery> Goods_Delivery { get; set; }
        public virtual Product_Put Product_Put { get; set; }
        public virtual Purchase_Put Purchase_Put { get; set; }
    }
}
