//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_Delivery
    {
        public int DeliveryId { get; set; }
        public Nullable<int> GoodsInvenid { get; set; }
        public Nullable<int> Saleid { get; set; }
        public string productname { get; set; }
        public Nullable<int> Delivery_date { get; set; }
        public Nullable<int> Outbound_number { get; set; }
        public string State { get; set; }
        public string Handlers { get; set; }
        public Nullable<int> Usersid { get; set; }
        public string Purposes { get; set; }
        public string Tips { get; set; }
    
        public virtual Goods_inventory Goods_inventory { get; set; }
        public virtual Sales Sales { get; set; }
        public virtual Users Users { get; set; }
    }
}
