//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lnven
    {
        public Lnven()
        {
            this.Goods = new HashSet<Goods>();
            this.Products = new HashSet<Products>();
        }
    
        public int Invenid { get; set; }
        public string Invenname { get; set; }
    
        public virtual ICollection<Goods> Goods { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
