//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int Materialid { get; set; }
        public Nullable<int> Goodsid { get; set; }
        public Nullable<int> Departmentid { get; set; }
        public Nullable<int> Materialcount { get; set; }
        public Nullable<System.DateTime> Material_time { get; set; }
        public string Material_use { get; set; }
        public string State { get; set; }
        public string Material_member { get; set; }
        public Nullable<int> Usersid { get; set; }
        public string Tips { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Goods Goods { get; set; }
        public virtual Users Users { get; set; }
    }
}
