//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrderManager = new HashSet<OrderManager>();
            this.Sales = new HashSet<Sales>();
        }
    
        public int Productsid { get; set; }
        public string Productsname { get; set; }
        public string Productsjieche { get; set; }
        public string Unit { get; set; }
        public string Address { get; set; }
        public string Specifications { get; set; }
        public string Packaging { get; set; }
        public string Batch_number { get; set; }
        public string Titanic { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string SupplierId { get; set; }
        public Nullable<int> Category { get; set; }
        public string Tips { get; set; }
    
        public virtual Lnven Lnven { get; set; }
        public virtual ICollection<OrderManager> OrderManager { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
