//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_order
    {
        public Purchase_order()
        {
            this.Good_Quality = new HashSet<Good_Quality>();
            this.Purchase__Brrowing = new HashSet<Purchase__Brrowing>();
            this.Purchase_brrowing = new HashSet<Purchase_brrowing>();
            this.Purchase_Put = new HashSet<Purchase_Put>();
            this.Purchase_returns = new HashSet<Purchase_returns>();
        }
    
        public int Purchase_orderid { get; set; }
        public Nullable<int> Goodsid { get; set; }
        public Nullable<int> Procurement_number { get; set; }
        public string Settlement_method { get; set; }
        public Nullable<decimal> Amount_payable { get; set; }
        public Nullable<decimal> Real_pay { get; set; }
        public Nullable<decimal> Unpaid_amount { get; set; }
        public Nullable<System.DateTime> Purchase_date { get; set; }
        public Nullable<decimal> Purchase_money { get; set; }
        public string State { get; set; }
        public string Handlers { get; set; }
        public Nullable<int> Usersid { get; set; }
        public string Tips { get; set; }
    
        public virtual ICollection<Good_Quality> Good_Quality { get; set; }
        public virtual Goods Goods { get; set; }
        public virtual ICollection<Purchase__Brrowing> Purchase__Brrowing { get; set; }
        public virtual ICollection<Purchase_brrowing> Purchase_brrowing { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Purchase_Put> Purchase_Put { get; set; }
        public virtual ICollection<Purchase_returns> Purchase_returns { get; set; }
    }
}
