//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int SalaryId { get; set; }
        public Nullable<int> EmployeesId { get; set; }
        public Nullable<int> Base_salary { get; set; }
        public Nullable<int> Lunch_subsidies { get; set; }
        public Nullable<int> Taken { get; set; }
        public Nullable<int> The_fines { get; set; }
        public Nullable<int> Housing_subsidies { get; set; }
        public Nullable<int> Additional_benefits { get; set; }
        public Nullable<int> Thetax_amount { get; set; }
        public Nullable<int> Total_amount { get; set; }
        public Nullable<System.DateTime> Issuing_date { get; set; }
        public string Bankname { get; set; }
        public string Salary_account { get; set; }
        public Nullable<System.DateTime> Salary_stardate { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
