//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Goods = new HashSet<Goods>();
        }
    
        public int SupplierId { get; set; }
        public string Supplier_name { get; set; }
        public string Supplier__Introduction { get; set; }
        public string Postal_code { get; set; }
        public Nullable<int> Credibility { get; set; }
        public string Quality_state { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public string Tel { get; set; }
        public string Deposit_bank { get; set; }
        public Nullable<int> Bank_number { get; set; }
        public string Fax { get; set; }
        public string E_mail { get; set; }
    
        public virtual ICollection<Goods> Goods { get; set; }
    }
}
