//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Good_Quality = new HashSet<Good_Quality>();
            this.Goods_Delivery = new HashSet<Goods_Delivery>();
            this.Material = new HashSet<Material>();
            this.OrderManager = new HashSet<OrderManager>();
            this.PlanOrder = new HashSet<PlanOrder>();
            this.Product = new HashSet<Product>();
            this.Product_Quality = new HashSet<Product_Quality>();
            this.Purchase_brrowing = new HashSet<Purchase_brrowing>();
            this.Purchase_order = new HashSet<Purchase_order>();
            this.Purchase_Put = new HashSet<Purchase_Put>();
            this.Purchase_Return = new HashSet<Purchase_Return>();
            this.Purchase_returns = new HashSet<Purchase_returns>();
            this.Sales = new HashSet<Sales>();
            this.Sales_Brrowing = new HashSet<Sales_Brrowing>();
            this.Sales_delivery = new HashSet<Sales_delivery>();
        }
    
        public int Usersid { get; set; }
        public string Usersname { get; set; }
        public string UserReadname { get; set; }
        public string Users_password { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Start_time { get; set; }
        public Nullable<int> Department { get; set; }
        public string Image { get; set; }
        public int Post { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual ICollection<Good_Quality> Good_Quality { get; set; }
        public virtual ICollection<Goods_Delivery> Goods_Delivery { get; set; }
        public virtual ICollection<Material> Material { get; set; }
        public virtual ICollection<OrderManager> OrderManager { get; set; }
        public virtual ICollection<PlanOrder> PlanOrder { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<Product_Quality> Product_Quality { get; set; }
        public virtual ICollection<Purchase_brrowing> Purchase_brrowing { get; set; }
        public virtual ICollection<Purchase_order> Purchase_order { get; set; }
        public virtual ICollection<Purchase_Put> Purchase_Put { get; set; }
        public virtual ICollection<Purchase_Return> Purchase_Return { get; set; }
        public virtual ICollection<Purchase_returns> Purchase_returns { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
        public virtual ICollection<Sales_Brrowing> Sales_Brrowing { get; set; }
        public virtual ICollection<Sales_delivery> Sales_delivery { get; set; }
    }
}
